name: On PR

on:
  pull_request:
    types: [ opened, reopened, synchronize, edited ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v1
      - name: Set up Go environment
        uses: actions/setup-go@v2
        with:
          go-version: '^1.17.4'
      - name: Build
        run: |
          go build ./...
